# Generated by Django 2.2 on 2022-02-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameType', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('startTime', models.TimeField(auto_now=True)),
                ('endTime', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(max_length=2500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to='eventsApp.User')),
                ('participants', models.ManyToManyField(related_name='games', to='eventsApp.User')),
            ],
        ),
    ]
